server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&verifyServerCertificate=false&serverTimezone=UTC
    username: root
    password: 030218
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml